name: Publish OpenDORA Backstage Plugin NPM Package

on:
  workflow_dispatch:
  release:
    types: [published]
    branches:
      - main
    paths:
      - "backstage-plugin/**"
      - ".github/workflows/publish-backstage-plugin-workflow.yaml"

jobs:
  publish:
    name: install, lint, format, type-check, build, test, publish
    runs-on: ubuntu-latest
    timeout-minutes: 20

    defaults:
      run:
        working-directory: backstage-plugin
    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: backstage-plugin/yarn.lock
          registry-url: https://npm.pkg.github.com/
          always-auth: true

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: validate config
        run: yarn backstage-cli config:check --lax

      - name: lint
        run: yarn lint:all

      - name: format
        run: yarn prettier:check

      - name: type checking and declarations
        run: yarn tsc

      - name: build
        run: yarn build:all

      - name: test
        run: yarn test:all

      - name: publish
        working-directory: backstage-plugin/plugins/open-dora
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
